[package]
name = "chardet"
version = "0.2.1"
authors = ["thuleqaid <thuleqaid@163.com>"]
readme = "README.md"
repository = "https://github.com/thuleqaid/rust-chardet"

description = "rust version of chardet"
license = "LGPL-3.0"

[dependencies]
